app = "your-app-name"  # 실제 앱 이름으로 변경

[build]
dockerfile = "Dockerfile"

[env]
PORT = "3000"

[vm]
memory = 1024         # 1GB로 설정
cpu_kind = "shared"
cpus = 1

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = false
auto_start_machines = true
min_machines_running = 1
