name: Deploy to Oracle Cloud

on:
  push:
    branches:
      - main

env:
  DOCKER_REPO: ${{ secrets.DOCKER_USERNAME }}/front-linkup-app

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      packages: read
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_REPO }}:${{ github.sha }},${{ env.DOCKER_REPO }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Deploy to Oracle Cloud via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_SSH_USERNAME }}
          key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          script: |
            sudo usermod -aG docker ${{ secrets.SERVER_SSH_USERNAME }}
            sudo chown ${{ secrets.SERVER_SSH_USERNAME }}:${{ secrets.SERVER_SSH_USERNAME }} /var/run/docker.sock

            docker stop app-container || true
            echo "기존 컨테이너 중지 완료"

            docker rm app-container || true
            echo "기존 컨테이너 제거 완료"

            docker pull ${{ env.DOCKER_REPO }}:latest
            echo "Docker 이미지 풀링 완료"

            docker run -d \
              --name app-container \
              -p 3000:3000 \
              -e API_URL="${{secrets.API_URL}}" \
              -e NODE_ENV="${{secrets.NODE_ENV}}" \
              -e OAUTH_REDIRECT_URI="${{secrets.OAUTH_REDIRECT_URI}}" \
              ${{ env.DOCKER_REPO }}:latest

            echo "새 컨테이너 실행 완료"

            docker image prune -af
            echo "사용하지 않는 이미지 전체 정리 완료"